# Generated by Django 4.2 on 2025-01-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_date',
        ),
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
