# Generated by Django 4.2 on 2025-01-19 21:08

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_order_is_active_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tour',
            name='gif',
            field=models.CharField(default='hero.gif', max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 1, 19)),
            preserve_default=False,
        ),
    ]
