# Generated by Django 5.1.5 on 2025-01-23 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tour_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tour',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='tour_gifs/'),
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_day_images/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tours.tour')),
            ],
        ),
    ]
