# Generated by Django 5.1.5 on 2025-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_remove_tour_latitude_remove_tour_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.AddField(
            model_name='tour',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='tours_gifs/'),
        ),
        migrations.AlterField(
            model_name='tourday',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
