# Generated by Django 5.1.5 on 2025-01-23 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_remove_tour_duration_tour_latitude_tour_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ключевого момента')),
                ('icon', models.CharField(choices=[('bi-geo-alt-fill', 'Геолокация'), ('bi-calendar-check-fill', 'Календарь'), ('bi-star-fill', 'Звезда'), ('bi-check-circle-fill', 'Галочка')], default='bi-star-fill', max_length=50, verbose_name='Иконка (Bootstrap Icons)')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_points', to='tours.tourday')),
            ],
        ),
    ]
