# Generated by Django 5.1.5 on 2025-01-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='important_fact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='interesting_fact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
